version: '3'
services:
  php:
    build: .
    image: my/php7.2
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - app-data:/var/www/

volumes:
  app-data:
    driver_opts:
      type: none
      device: ${PWD}/www/
      o: bind
